### PR TITLE
Better onboarding

### PR DESCRIPTION
**Pull request by FergusFettes**
Added a main.py and index.html, but its taking forever to run so absent data to test it with not sure if this will work. I think I might just quickly rewrite this with some optimizations. But maybe you find this useful. I'll update this with the working index.html if I manage to test it.

### CODE REVIEW

**Comment by FergusFettes** [comment]
damn I got majorly nerd-sniped on this and spent all day on it. but i got a really nice result, ill share it with you soon.

but in the end i just rewrote everything. I think im doing the same thing as you at the end of the day, currently running a full noken output on gptj so i can verify. also got it working with mistral and gpt2

afaict, [this](https://github.com/FergusFettes/latent-cartography/blob/main/demo.py) pretty much does everything you are doing. im using a new interp library called nnsight, which has quite nice ergonomics. i spent a while trying to do clever optimizations, like running all the forward passes in the same context but it was too hard.

**Comment by FergusFettes** [comment]
image
weve got a hit! but its 1MB and the browser is refusing to display it all :/

ah it loaded!
image

ill need to fix this up somehow so i can scroll around in the full 1MB. should be possible.

here is a smaller example: https://www.fergusfettes.com/latent-cartography/

**Comment by mwatkins1970** [comment]
Excellent work! Thanks for making the effort of dealing with my appalling code : )
I'm assuming
https://www.fergusfettes.com/latent-cartography/
is also a definition tree for the centroid? Just with a lower probability cutoff? (Hence no 'penis'.)



________________________________

**Comment by FergusFettes** [comment]
probably yes. i was running tests with other words but it sure looks like the centroid.

did you try doing some kind of sentiment analysis to the branches? that could be an interesting way to filter them, and should be fastish.

do you have access to gpus? i ran the gptj thing out to 1e-6 in maybe an hour or two.

**Comment by FergusFettes** [comment]
what kind of speed do you get? i just put in an iterator timery thingy and im doing about 3iterations/s with gptj on GPU

**Comment by mwatkins1970** [comment]
It sounds like you're running about 3X faster than me. I'm using Colab, with TPUs when they're available. But I barely know what I'm doing here! I rather unexpectedly got recruited into AI safety work and only got back into coding in the last year or so (something I was doing back in the 1980s). I'm figuring out everything as I go (and using ChatGPT4 a lot) which is why my code is so clunky. And all these platforms (Colab, Github, etc.) are still something of a mystery...

I've not tried sentiment analysis, sounds like a worthwhile thing to pursue. I have too many research threads right now! But I might get around to that. Keep me posted of anything further you find/build.

Right now I'm trying to build animated definition trees from trajectories through embedding space (token-to-token or centroid-to-token). Building the still image frames is instantaneous, but building all the JSON files for the intermediate points is very time consuming. So I'd be interested in any possible ways I could speed this up.

Also, if you could figure out a quick and easy way to do it, i'd be interested to see how the definition trees look for the token centroids in GPT2-xl and GPT2-small.

**Comment by mwatkins1970** [comment]
Actually it looks like you're running more like 10X my speed (it's about 3 seconds per iteration at the moment (and that's using a T4 GPU via Colab). Am I doing something wrong here?

**Comment by FergusFettes** [comment]
Check out what I've got so far :)

https://www.fergusfettes.com/latent-cartography/

I'm pretty damn proud if it tbh.

I decided to just add 'a man' and 'a woman' at the end to see what those regions look like, and ran it for a few models.

For eg. the Mistral centroid with >21000 tokens, it takes a minute to load but its not so bad after that if you don't use the search function.

Left click on a node to go in, right click to go back to main.

I like your posts, so I'd be down to collab if you like.

Regarding whether you are doing anything wrong, I'm not sure tbh, I haven't really used pytorch much and I only looked at your code for long enough to figure out how I could copy it. I lucked into discovering nnsight which is just really really good so its easy to get things right. So I'd guess you are probably doing some little things wrong, and nnsight is doing them all right.

**Comment by FergusFettes** [comment]
The script I shared earlier should just work if you `pip install -r requirements.txt`. Maybe its already useful for you for what you are doing now, now sure I follow 100% but it sounds interesting.

https://github.com/FergusFettes/latent-cartography/blob/main/demo.py

**Comment by FergusFettes** [comment]
I also uploaded the jsons to huggingface: https://huggingface.co/datasets/fergusfettes/

which you should be able to access with 
```
from datasets import load_dataset

data = load_dataset("fergusfettes/gpt2_noken_1e-06_AtypicaldefinitionofXwouldbe")

data['train'][:5]
```

but it looks like I messed some of them up. This is the first time I've tried this. That one works. I'm going to be fiddling with datasets the next days so I'll try and fix them.

**Comment by mwatkins1970** [comment]
The interface is truly something to be proud of. It's doing some heavy computational lifting and regularly crashing the browser, but I'm sure this will get ironed out. I've just got lost in scrolling down the 'woman' and 'man' trees. The differences of emphasis are *so* interesting, revealing of some deep cultural infra-structure, as a result of a kind of averaging out of all text. I know some feminist thinkers that are going to love this!

**Comment by mwatkins1970** [comment]
One slight improvement would be to prune the tree JSON with a 
definition = definition.split("'.")[0]
definition = definition.split("',")[0]
kind of approach. That would get rid of a lot of "but" and "however" clauses that are cluttering the tree.
You could also pull any nodes which are ends of branches and consist solely of ".", "," or "'"

Amazing work so far, though, and yeah I'd love to collaborate. There's a lot of work to be done in this mapping of GPT embedding space, and I'm stretching my abilities and time just scraping the surface.

**Pull request closed without merging**
